//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KS2.EasySyncClient.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KS2.EasySyncClient.Resources.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application already started!.
        /// </summary>
        internal static string APP_ALREADY_STARTED {
            get {
                return ResourceManager.GetString("APP_ALREADY_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EasySync has started.
        /// </summary>
        internal static string APP_STARTED {
            get {
                return ResourceManager.GetString("APP_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string MENU_ABOUT {
            get {
                return ResourceManager.GetString("MENU_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Sync.
        /// </summary>
        internal static string MENU_DELETE {
            get {
                return ResourceManager.GetString("MENU_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the sync on : {0} ?.
        /// </summary>
        internal static string MENU_DELETE_CONFIRMATION {
            get {
                return ResourceManager.GetString("MENU_DELETE_CONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Sync.
        /// </summary>
        internal static string MENU_EDIT {
            get {
                return ResourceManager.GetString("MENU_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string MENU_EXIT {
            get {
                return ResourceManager.GetString("MENU_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Log.
        /// </summary>
        internal static string MENU_LOG {
            get {
                return ResourceManager.GetString("MENU_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new site.
        /// </summary>
        internal static string MENU_NEW_SITE {
            get {
                return ResourceManager.GetString("MENU_NEW_SITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Local Folder.
        /// </summary>
        internal static string MENU_OPEN_FOLDER {
            get {
                return ResourceManager.GetString("MENU_OPEN_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string MENU_OPTIONS {
            get {
                return ResourceManager.GetString("MENU_OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sites.
        /// </summary>
        internal static string MENU_SITES {
            get {
                return ResourceManager.GetString("MENU_SITES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Sync.
        /// </summary>
        internal static string MENU_START {
            get {
                return ResourceManager.GetString("MENU_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Sync.
        /// </summary>
        internal static string MENU_STOP {
            get {
                return ResourceManager.GetString("MENU_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connector available.
        /// </summary>
        internal static string STEP0_ERROR1 {
            get {
                return ResourceManager.GetString("STEP0_ERROR1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        internal static string STEP0_FINISH {
            get {
                return ResourceManager.GetString("STEP0_FINISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next -&gt;.
        /// </summary>
        internal static string STEP0_NEXT {
            get {
                return ResourceManager.GetString("STEP0_NEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill-in the server URL.
        /// </summary>
        internal static string STEP1_ERROR1 {
            get {
                return ResourceManager.GetString("STEP1_ERROR1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill-in your login.
        /// </summary>
        internal static string STEP1_ERROR2 {
            get {
                return ResourceManager.GetString("STEP1_ERROR2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill-in your password.
        /// </summary>
        internal static string STEP1_ERROR3 {
            get {
                return ResourceManager.GetString("STEP1_ERROR3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connector Init failed.
        /// </summary>
        internal static string STEP1_ERROR4 {
            get {
                return ResourceManager.GetString("STEP1_ERROR4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect to repository.
        /// </summary>
        internal static string STEP1_ERROR5 {
            get {
                return ResourceManager.GetString("STEP1_ERROR5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This site is already synchonized. Please select another one.
        /// </summary>
        internal static string STEP2_ERROR1 {
            get {
                return ResourceManager.GetString("STEP2_ERROR1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a folder.
        /// </summary>
        internal static string STEP3_ERROR1 {
            get {
                return ResourceManager.GetString("STEP3_ERROR1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This folder or one of its subfolders is already used for syncing. Please select another one..
        /// </summary>
        internal static string STEP3_ERROR2 {
            get {
                return ResourceManager.GetString("STEP3_ERROR2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This folder contains subfolders or files. Are you sure you want to proceed ?.
        /// </summary>
        internal static string STEP3_ERROR3 {
            get {
                return ResourceManager.GetString("STEP3_ERROR3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update is available. Do you want to install it now ?.
        /// </summary>
        internal static string UPDATE_AVAILABLE_BODY {
            get {
                return ResourceManager.GetString("UPDATE_AVAILABLE_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KS² EasySync Update available.
        /// </summary>
        internal static string UPDATE_AVAILABLE_TITLE {
            get {
                return ResourceManager.GetString("UPDATE_AVAILABLE_TITLE", resourceCulture);
            }
        }
    }
}
